<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\droppy\Entity\Droppy;
use Drupal\system\Entity\Menu;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function droppy_form_menu_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $config_list = Droppy::getConfigList();

  /** @var Drupal\system\Entity\Menu $entity */
  $entity = $form_state->getFormObject()->getEntity();

  $form['droppy'] = array(
    '#type' => 'details',
    '#title' => t('Drop-down'),
    '#weight' => 1
  );

  $form['droppy']['droppy_enable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable'),
    '#description' => t('Make this menu a drop-down menu.'),
    '#default_value' => $entity->getThirdPartySetting('droppy', 'droppy_enable')
  );

  $form['droppy']['droppy_config'] = array(
    '#type' => 'select',
    '#title' => t('Options'),
    '#description' => t('Choose the Droppy configuration to associate with this menu.'),
    '#options' => $config_list,
    '#default_value' => $entity->getThirdPartySetting('droppy', 'droppy_config')
  );

  $form['#entity_builders'][] = 'droppy_form_menu_form_builder';

  // Move links at the bottom.
  $form['links']['#weight'] = 2;
}

/**
 * Entity builder for the menu configuration entity.
 */
function droppy_form_menu_form_builder($entity_type, Menu $entity, &$form, FormStateInterface $form_state) {

  $entity->setThirdPartySetting('droppy', 'droppy_enable', $form_state->getValue('droppy_enable'));
  $entity->setThirdPartySetting('droppy', 'droppy_config', $form_state->getValue('droppy_config'));
}

/**
 * Implements hook_preprocess_menu().
 */
function droppy_preprocess_menu(&$variables) {

  // TODO - [ ] If menu_name is not set, add a log message.
  if (!isset($variables['menu_name'])) {
    return;
  }

  /** @var Menu $entity */
  $entity = Menu::load($variables['menu_name']);

  // If menu doesn't use Droppy, return.
  if (!$entity->getThirdPartySetting('droppy', 'droppy_enable')) {
    return;
  }

  // Load the Droppy config entity.
  /** @var \Drupal\droppy\Entity\DroppyInterface $entity */
  $entity = Droppy::load($entity->getThirdPartySetting('droppy', 'droppy_config'));
  $config = $entity->get('id');

  // If not exists, add the current option to drupalSettins.
  if (!isset($variables['#attached']['drupalSettings']['droppy'][$config])) {
    $variables['#attached']['drupalSettings']['droppy'][$config] = $entity->getOptions();
  }

  // Add Flickity attribute and attach the library.
  $variables['attributes']['data-droppy-options'] = $config;
  $variables['#attached']['library'][] = 'droppy/droppy';

  // Add cacheability metadata.
  if (isset($variables['#cache']['tags'])) {
    $variables['#cache']['tags'] = array_merge($variables['#cache']['tags'], $entity->getCacheTagsToInvalidate());
  }
  else {
    $variables['#cache']['tags'] = $entity->getCacheTagsToInvalidate();
  }
}
