droppy.droppy.*:
  type: config_entity
  label: 'Droppy configuration'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    options:
      type: mapping
      label: 'Options'
      mapping:
        dropdownSelector:
          type: string
          label: 'Dropdown selector'
        parentSelector:
          type: string
          label: 'Parent selector'
        triggerSelector:
          type: string
          label: 'Trigger selector'
        closeOthers:
          type: boolean
          label: 'Close others'
        clickOutToClose:
          type: boolean
          label: 'Click out to close'
        clickEscToClose:
          type: boolean
          label: 'Click ESC to close'
        animationIn:
          type: string
          label: 'Animation in'
        animationOut:
          type: string
          label: 'Animation out'
        preventDefault:
          type: boolean
          label: 'Prevent default'

system.menu.*.third_party.droppy:
  type: mapping
  label: 'Droppy options'
  mapping:
    droppy_enable:
      type: boolean
      label: 'Droppy enable'
    droppy_options:
      type: string
      label: 'Config ID'
